language: python
python:
    - "2.7"
    - "3.3"

install:
    - "pip install -r requirements.txt"
    - "pip install sphinx"
    - "pip install sphinx_rtd_theme"
    - "pip install -e git+https://github.com/numpy/numpydoc.git"
    - "pip install ."

script:
    - nosetests
    - cd doc && make doctest
